
POST http://localhost:3000/api/tasks HTTP/1.1
content-type: application/json

{
"id": 4,
"title": "Unit Test1",
"tag": 4,
"tag_name": "tag4"
}

###



POST http://localhost:3000/api/tasks/1 HTTP/1.1
content-type: application/json

{
"title": "Unit Test4",
"tag_name": "tag4"
}
